title: Blog do Rodrigo Ghedin
description: Blog pessoal de Rodrigo Ghedin. Anedotas, reflexões e trechos de obras de gente esperta e/ou inspiradora.
email: ghedin@gmail.com
permalink: /:title/
markdown: kramdown
theme: jekyll-theme-minimal
timezone: UTC−03:00
future: false
paginate: 10
gems:
  - jekyll-feed
  - jekyll-paginate
